[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dev-time"
version = "0.0.1"
dependencies = [
    "typer",
    "sqlmodel",
    'importlib-metadata; python_version>"3.10"',
]

[project.scripts]
dev-time = "dev_time.main:main"
